apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-propagator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jephilli-tenant/devfile-sample-go-basic/governance-policy-propagator@sha256:5d32082d40fe002e8d06ff0599116dac776fb820fe1105b3cb8cf548a7ceef7e
        name: container-image
        resources: {}
status: {}
