apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: governance-policy-propagator
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: governance-policy-propagator
status:
  loadBalancer: {}
